### ISSUE TITLE
Not all file types are Submitted

### ISSUE THREAD

**Issue by steven1350** [pressbooks/excalibur#13]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/excalibur/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fexcalibur) to see if your bug or enhancement is already listed?

### Description

Upon successful submission of an item to DSpace, not all of the file formats created in Pressbooks are submitted to DSpace. 

Notably absent are formats such as "Pressbooks XML" and "Wordpress XML" (which are labeled as WXR files in the list of exported files in Pressbooks) 

Sidenote: This request is from Ryerson University

### Steps to Reproduce

1. In Pressbooks, export a Book into desired formats, being sure to check Pressbooks XML and/or WordPress XML
2. Submit the item to DSpace

**Expected behavior:** All formats are exported to DSpace

**Actual behavior:** WXR formats are not submitted to DSpace

**Comment by connerbw** [comment]
In my tests with Dspace not all the file types worked.

The code in `excalibur/inc/dspace/class-deposit.php` defines that this plugin only supports:

```php
	static public $supportedExportTypes = [
		'pdf',
		'print-pdf',
		'epub',
		'epub3',
		'mobi',
		'xhtml',
	];
```

Where `supportedExportTypes` are array keys from the following filter in In `\Pressbooks\Utility\latest_exports`:

```php
	$filetypes = apply_filters(
		'pb_latest_export_filetypes', [
			'epub3' => '._3.epub',
			'epub' => '.epub',
			'pdf' => '.pdf',
			'print-pdf' => '._print.pdf',
			'mobi' => '.mobi',
			'icml' => '.icml',
			'htmlbook' => '.-htmlbook.html',
			'xhtml' => '.html',
			'wxr' => '.xml',
			'vanillawxr' => '._vanilla.xml',
			'mpdf' => '._oss.pdf',
			'odf' => '.odt',
		]
	);
```

Can you modify  `$supportedExportTypes`, add `'wxr', 'vanillawxr'`, and tell me if it works for you?

If yes, are you recommending we support all files?

**Comment by SteelWagstaff** [comment]
@steven1350 -- we just got an email request from one of your colleague at eCampus Ontario on this issue. Some clarification would help me as I work on a response, namely, were you able to modify the array as suggested by @connerbw above? If so, do you have answers to the two questions posed?

**Comment by steven1350** [comment]
I have added the values to the `$supportedExportTypes` array, however this didn't seem to have any effect on the files sent on a SWORD deposit

**Comment by steven1350** [comment]
I have modified the file as requested, and I can confirm that the XML files are now successfully transferring as expected
