### ISSUE TITLE
Fix build process

### ISSUE THREAD

**Issue by connerbw** [pressbooks/excalibur#7]
Add the release asset build script to Travis.

Then whenever we tag a version there’s a downloadable release which includes all the Composer dependencies.

Need help from @greatislander

**Comment by connerbw** [comment]
TODO: Package latest version when Pressbooks 5 is released.

**Comment by greatislander** [comment]
Fixed in https://github.com/pressbooks/excalibur/commit/4d5d35766afa0eb04865df8f0fad6c48db12a332.
